Tower: With 4 rings
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 3 from A to B
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 4 from A to C
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 3 from B to C
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Tower: With 6 rings
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 3 from A to B
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 4 from A to C
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 3 from B to C
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 5 from A to B
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 3 from C to A
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 4 from C to B
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 3 from A to B
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 6 from A to C
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 3 from B to C
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 4 from B to A
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 3 from C to A
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 5 from B to C
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
Ring 3 from A to B
Ring 1 from C to A
Ring 2 from C to B
Ring 1 from A to B
Ring 4 from A to C
Ring 1 from B to C
Ring 2 from B to A
Ring 1 from C to A
Ring 3 from B to C
Ring 1 from A to B
Ring 2 from A to C
Ring 1 from B to C
